---
title: "About"
author: "Abhik Seal & Chris Peters"
date: "June 27, 2015"
output: html_document
---
There are from adverse events related to medicine listed in the API, so I hope you'll agree that public awareness and understanding of the risks associated with pharmaceuticals are a worthy endeavor.

### Limitations

-  The actual reports are not very standardized, erroneous data are common.
-  Reports commonly list multiple drugs and multiple reactions, so there is not way to know if a certain drug caused a certain reaction. Here's a highly simplified example of [how reports are filled out](https://open.fda.gov/drug/event/#adverse-event-reports).
-  The data typically lag by six months, so this isn't recent data.
-  There's no measure of drugs dispensed, so actual counts reflect some mix of how common a drug is and how often reports are filed.
-  This dataset is limited to events that are actually reported, some drugs might be systematically reported more or less often.

### FDA Adverse Event Reporting System (FAERS) Database

The <a href="http://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/">FDA FAERS system</a> is a database of adverse events (basically, drug reactions and medication error reports). The FDA uses the database in its post-marketing surveillance program.

### OpenFDA

In early 2014, <a href="https://open.fda.gov/update/introducing-openfda/">the FDA released an API</a> to make adverse event reports, labels, and eforcement reports more accessible.


### R packages used
-  Shiny [https://github.com/rstudio/shiny-server](https://github.com/rstudio/shiny-server)
-  rOpenSci/openfda [https://github.com/ropenhealth/openfda](https://github.com/ropenhealth/openfda)
-  ggplot2 [https://github.com/hadley/ggplot2](https://github.com/hadley/ggplot2)
-  scales [https://github.com/hadley/scales](https://github.com/hadley/scales)
-  dplyr [https://github.com/hadley/dplyr](https://github.com/hadley/dplyr)
-  reshape2 [https://github.com/hadley/reshape](https://github.com/hadley/reshape)
-  ggthemes [https://github.com/jrnold/ggthemes](https://github.com/jrnold/ggthemes)

